/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './navbar/navbar.component.ngfactory';
import * as i3 from './navbar/navbar.component';
import * as i4 from '@angular/router';
import * as i5 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'navbar',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_NavbarComponent_0,i2.RenderType_NavbarComponent)),
      i1.ɵdid(1,114688,(null as any),0,i3.NavbarComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(3,
          0,(null as any),(null as any),4,'div',[['class','container']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
          (null as any),['\n  '])),(_l()(),i1.ɵeld(5,16777216,(null as any),(null as any),
          1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),i1.ɵdid(6,212992,(null as any),0,i4.RouterOutlet,
          [i4.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i1.ɵted(-1,(null as any),['\n']))],(_ck,_v) => {
    _ck(_v,1,0);
    _ck(_v,6,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(1,49152,(null as any),0,i5.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i5.AppComponent> = i1.ɵccf('app-root',
    i5.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2phbWVzLndhbmcvTXlTcGFjZS9teWxhYnMvTEFCLVVkZW15L0FuZ3VsYXIyKy9UaGUgQ29tcGxldGUgQW5ndWxhciBDb3Vyc2UgLSBCZWdpbm5lciB0byBBZHZhbmNlZC9zZWNfMTIvZGVwbG95LWRlbW8vc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2phbWVzLndhbmcvTXlTcGFjZS9teWxhYnMvTEFCLVVkZW15L0FuZ3VsYXIyKy9UaGUgQ29tcGxldGUgQW5ndWxhciBDb3Vyc2UgLSBCZWdpbm5lciB0byBBZHZhbmNlZC9zZWNfMTIvZGVwbG95LWRlbW8vc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvamFtZXMud2FuZy9NeVNwYWNlL215bGFicy9MQUItVWRlbXkvQW5ndWxhcjIrL1RoZSBDb21wbGV0ZSBBbmd1bGFyIENvdXJzZSAtIEJlZ2lubmVyIHRvIEFkdmFuY2VkL3NlY18xMi9kZXBsb3ktZGVtby9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2phbWVzLndhbmcvTXlTcGFjZS9teWxhYnMvTEFCLVVkZW15L0FuZ3VsYXIyKy9UaGUgQ29tcGxldGUgQW5ndWxhciBDb3Vyc2UgLSBCZWdpbm5lciB0byBBZHZhbmNlZC9zZWNfMTIvZGVwbG95LWRlbW8vc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxuYXZiYXI+PC9uYXZiYXI+XG48ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gIDxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cbjwvZGl2PiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQSxlQUFpQiwwQ0FDakI7VUFBQTtVQUFBLDBEQUF1QjtVQUFBLHlCQUNyQjtVQUFBO1VBQUEscUNBQUE7VUFBQTtjQUFBO01BQStCO0lBRmpDO0lBRUU7Ozs7b0JDRkY7TUFBQTthQUFBO1VBQUE7OzsifQ==
